module StateHelper
  def state_helper(member_state)
    states = [%w[AK Alaska],
              %w[AL Alabama],
              %w[AR Arkansas],
              ['AS', 'American Samoa'],
              %w[AZ Arizona],
              %w[CA California],
              %w[CO Colorado],
              %w[CT Connecticut],
              ['DC', 'District of Columbia'],
              %w[DE Delaware],
              %w[FL Florida],
              %w[GA Georgia],
              %w[GU Guam],
              %w[HI Hawaii],
              %w[IA Iowa],
              %w[ID Idaho],
              %w[IL Illinois],
              %w[IN Indiana],
              %w[KS Kansas],
              %w[KY Kentucky],
              %w[LA Louisiana],
              %w[MA Massachusetts],
              %w[MD Maryland],
              %w[ME Maine],
              %w[MI Michigan],
              %w[MN Minnesota],
              %w[MO Missouri],
              %w[MS Mississippi],
              %w[MT Montana],
              ['NC', 'North Carolina'],
              ['ND', 'North Dakota'],
              %w[NE Nebraska],
              ['NH', 'New Hampshire'],
              ['NJ', 'New Jersey'],
              ['NM', 'New Mexico'],
              %w[NV Nevada],
              ['NY', 'New York'],
              %w[OH Ohio],
              %w[OK Oklahoma],
              %w[OR Oregon],
              %w[PA Pennsylvania],
              ['PR', 'Puerto Rico'],
              ['RI', 'Rhode Island'],
              ['SC', 'South Carolina'],
              ['SD', 'South Dakota'],
              %w[TN Tennessee],
              %w[TX Texas],
              %w[UT Utah],
              %w[VA Virginia],
              ['VI', 'Virgin Islands'],
              %w[VT Vermont],
              %w[WA Washington],
              %w[WI Wisconsin],
              ['WV', 'West Virginia'],
              %w[WY Wyoming]]

    states.select { |state| state[0].include?(member_state) }.map { |state| state[1] }.join('')
  end


end
